// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDistroFromDockerImage(arg1) {
  return window["go"]["app"]["App"]["CreateDistroFromDockerImage"](arg1);
}

export function CreateDistroFromTarFile(arg1) {
  return window["go"]["app"]["App"]["CreateDistroFromTarFile"](arg1);
}

export function GetDistros() {
  return window["go"]["app"]["App"]["GetDistros"]();
}

export function GetDockerContainers() {
  return window["go"]["app"]["App"]["GetDockerContainers"]();
}

export function IsDockerDaemonRunning() {
  return window["go"]["app"]["App"]["IsDockerDaemonRunning"]();
}

export function SelectFile() {
  return window["go"]["app"]["App"]["SelectFile"]();
}

export function SelectFolder() {
  return window["go"]["app"]["App"]["SelectFolder"]();
}
