// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { app } from "../models";

export function CreateDistroFromDockerContainer(
  arg1: app.CreateDistroFromContainerRequest
): Promise<void>;

export function CreateDistroFromDockerImage(
  arg1: app.CreateDistroFromImageRequest
): Promise<void>;

export function CreateDistroFromTarFile(
  arg1: app.CreateDistroFromTarFileRequest
): Promise<void>;

export function GetDistros(): Promise<Array<app.Distro>>;

export function GetDockerContainers(): Promise<Array<app.Container>>;

export function IsDockerDaemonRunning(): Promise<boolean>;

export function SelectFile(): Promise<string>;

export function SelectFolder(): Promise<string>;
